[WIP] Add docs for binary caching troubleshooting
microsoft/vcpkg-docs pull request #132
Opened 2023-08-17 05:44 UTC by dan-shaw

2023-08-29 19:15 UTC, vicroms requested changes
Partial review

2023-08-29 19:15 UTC, vicroms commented on vcpkg/users/binarycaching-troubleshooting.md
> +* CMake Toolchain: set `-DVCPKG_INSTALL_OPTIONS="--debug"` in your CMake call.
```suggestion
* CMake Toolchain: set `-DVCPKG_INSTALL_OPTIONS="--debug"` in your `cmake` command call or in your `CMakePresets.json` file.
```

I think we should also start recommending setting these variables in `CMakePresets.json`.

2023-09-07 23:20 UTC, AugP reviewed
Added some review comments

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +* Set `builtin-baseline` in your [vcpkg manifest](./users/manifests.md).
```suggestion
* Set `builtin-baseline` in your [vcpkg manifest](./reference/vcpkg-json.md#builtin-baseline).
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +* Set `builtin-baseline` in your [vcpkg manifest](./users/manifests.md).
I think this reference article is a better one to use here. I am not sure how to make anchor links work with Markdown though, someone should double check what I suggested above.

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +### The hash of the vcpkg internal CMake functions (vcpkg_from_github, vcpkg_copy_pdbs, vcpkg_fixup_pkgconfig, etc) changes between runs
```suggestion
### ABI hash of vcpkg CMake helper functions changes between runs
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +You are always pulling the latest internal CMake functions, which are used in the ABI calculation. This is probably also caused by cloning the latest vcpkg repo. We expect this issue to go away in th
```suggestion
Internal vcpkg helper functions like vcpkg_from_github, vcpkg_copy_pdbs, vcpkg_fixup_pkgconfig, etc. are used in the ABI calculation. If you are getting new ABI hashes for these ports, this is probably also caused by pulling the latest vcpkg repo. This issue will be addressed in a future update when these functions will be separately versioned.
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +* See the previous section on how to pin the vcpkg catalog to a specific commit.
I think it's okay to repeat the instructions here. The idea with an article like this is that the user scrolls through it and pauses on a heading that is applicable to them. They shouldn't have to scroll somewhere else to find the specific nugget of information they need.

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +### The version of CMake, Powershell, compiler version changes between runs
```suggestion
### Version of CMake, PowerShell, or your compiler changes between runs
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +Somehow, your environment changes between runs. To verify that this indeed is the issue, temporarily disable including the compiler hash in your ABI by setting `VCPKG_DISABLE_COMPILER_TRACKING` to `O
```suggestion
Somehow, your environment changes between runs. To verify that this indeed is the issue, temporarily disable including the compiler hash in your ABI by setting `VCPKG_DISABLE_COMPILER_TRACKING` to `ON` in your custom triplet. If the issue persists, fix tool versions with `--x-abi-tools-use-exact-versions`. It is not recommended to use these options in development or a production environment as they can cause errors that are very hard to diagnose.
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +In these cases, vcpkg is behaving correctly, we expect the ABI hashes to change if your toolchain changes. Rebuilds can be expensive, however, so we have recommendations for the following environment
```suggestion
In these cases, vcpkg is behaving correctly. It is expected for toolchain changes to cause ABI hash changes as well. Rebuilds can be expensive however, so we have some suggestions for the following environments:
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +* Visual Studio C++ Compiler Updates: Major, minor and even patch updates to the compiler will cause your library ABI to change.  To minimize this, stop automatic Visual Studio updates.
```suggestion
* Continuous integration systems: Some continuous integration systems (such as GitHub Hosted Runners) use images that can update your C/C++ compiler or CMake version periodically. To minimize this, choose a versioned stable image if possible.
* MSVC compiler updates: Major, minor and patch updates to the MSVC compiler will cause your library ABI hash to change. To minimize this, turn off automatic Visual Studio updates.
```

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +* Use `vcpkg export` to package your libraries instead (currently, only works in classic mode)
Isn't the export for manifest mode feature available now? Worth double checking.

2023-09-07 23:20 UTC, AugP commented on vcpkg/users/binarycaching-troubleshooting.md
> +* Have an auxiliary CI run that builds vcpkg libraries daily or weekly
```suggestion
* Have an auxiliary continuous integration run that builds vcpkg libraries on a regular cadence (e.g. daily or weekly)
```

2023-09-19 20:13 UTC, JavierMatosD commented on vcpkg/users/binarycaching-troubleshooting.md
> +---
We should add the other attribute, i.e., ms.prod, ms.author, ms.topic, etc.

2023-09-19 20:20 UTC, JavierMatosD requested changes

2023-09-19 20:20 UTC, JavierMatosD commented on vcpkg/users/binarycaching-troubleshooting.md
> +## Configuring your Binary Cache
Sometimes you have "Binary Cache" capitalized but other times you don't. I'm not opinionated on whether it should be capitalized, but they should be consistent.

2023-09-19 20:20 UTC, JavierMatosD commented on vcpkg/users/binarycaching-troubleshooting.md
> +Consider the case of using a NuGet feed as a binary cache.
Should we set up zones for the various binary caching providers?

2023-09-20 23:54 UTC, data-queue commented
Continuing this in #152

2023-09-20 23:54 UTC, closed without merging