Removed obsolete ms.prod tag, FAQ updates, and various other misc changes
microsoft/vcpkg-docs pull request #237
Opened 2024-01-11 00:47 UTC by AugP

Removed obsolete ms.prod tag (now superseded by ms.service tag in our central docfx.json file), various formatting fixes, and updated the FAQ to address some issues.

Also fixes #125

2024-01-11 18:30 UTC, AugP commented
Got a few more bugs to address on this PR before it's ready.

2024-01-12 00:51 UTC, ras0219-msft approved these changes

2024-01-12 00:51 UTC, ras0219-msft commented on vcpkg/commands/add.md
> +
Is this removal intended?

2024-01-12 00:51 UTC, ras0219-msft commented on vcpkg/commands/create.md
> +
Is this whitespace within the code block really intended?

2024-01-12 00:51 UTC, ras0219-msft commented on vcpkg/commands/create.md
> +#   See additional helpful variables in /docs/maintainers/vcpkg_common_definitions.md
Is this whitespace change consistent with the otuput of the tool?

2024-01-12 00:51 UTC, ras0219-msft commented on vcpkg/get_started/get-started-adding-to-registry.md
> +
Did you intend to add whitespace within the code block?

2024-01-26 00:40 UTC, vicroms requested changes
Please fix the code block with the missing delimiter to avoid issues with formatting. 
I made some suggestions for the FAQ article.

Other than that, it looks good to me.

2024-01-26 00:40 UTC, vicroms commented on vcpkg/about/faq.md
> +In general, there are two ways to manage your dependencies with vcpkg:
```suggestion
There are two ways to manage your dependencies with vcpkg:
```

2024-01-26 00:40 UTC, vicroms commented on vcpkg/about/faq.md
> +1. **Manifest mode** lets you declare your direct dependencies, version constraints, and registries used in a file called *vcpkg.json*. This file should be included in your code repo and can be check
```suggestion
1. **Manifest mode** lets you declare your direct dependencies, version constraints, and used registries in a file called [`vcpkg.json`](../reference/vcpkg-json.md). This file should be included in your code's repository and can be checked in to your source control system. Dependencies are installed in a subfolder named `vcpkg_installed`. This way, each code project can have its own set of dependencies; nothing is installed system-wide. You can run vcpkg in manifest mode by running `vcpkg install` (with no other arguments), or by taking advantage of the automatic [integration with MSBuild](../users/buildsystems/msbuild-integration.md) and [CMake projects](../users/buildsystems/cmake-integration.md). We recommend using manifests for your projects over classic mode in most cases, as you have better control over your dependencies. See our [manifest mode article](../concepts/manifest-mode.md) for more details.
```

2024-01-26 00:40 UTC, vicroms commented on vcpkg/about/faq.md
> +Yes. Follow [our packaging zlib example](../examples/packaging-zipfiles.md) for creating a portfile using a fake URL. Then, either pre-seed the `downloads\` folder with a zip containing your private
```suggestion
Yes. Follow [our packaging example](../get_started/get-started-packaging.md) to create your own port and see the [overlay ports](../concepts/overlay-ports.md) and [registries](../concepts/registries.md) documentation to learn how to manage your private ports.
```

2024-01-26 23:32 UTC, vicroms approved these changes

2024-01-26 23:32 UTC, merged