Add Concepts: Supported Hosts
microsoft/vcpkg-docs pull request #241
Opened 2024-01-17 03:48 UTC by BillyONeal

This adds a document describing how we think about which host platforms and configurations are expected to work with vcpkg.

2024-01-17 03:49 UTC, BillyONeal commented
> @BillyONeal : Thanks for your contribution! The author(s) have been notified to review your proposed change. @bion

Does this mean that the 'author' tag at the top should be my GitHub username?

2024-01-24 01:50 UTC, vicroms requested changes
Made some suggestions to avoid passive voice

2024-01-24 01:50 UTC, vicroms commented on vcpkg/concepts/supported-hosts.md
> +  configurations are rapidly found and fixed by vcpkg's maintainers and community.
```suggestion
  The configurations used to test vcpkg's curated registry on a regular basis. Problems in these configurations
  are rapidly found and fixed by vcpkg's maintainers and community..
```

2024-01-24 01:50 UTC, vicroms commented on vcpkg/concepts/supported-hosts.md
> +  substantially similar to one of the fully tested configurations.
```suggestion
  Configurations treated with the same priority as 'Full support, tested' but which are not part of the regular tests.
  In general, these configurations are substantially similar to one of the fully tested configurations.
```

2024-01-24 01:50 UTC, vicroms commented on vcpkg/concepts/supported-hosts.md
> +  interested in moving as many platforms out of community support into full support as possible.
```suggestion
  Configurations that are not actively supported by vcpkg's maintainers but have substantial community investment.
  vcpkg maintainers accept changes to fix problems for these platforms but don't make guarantees that these 
  configurations work. The vcpkg team is interested in moving as many platforms out of community support
  into full support as possible.
```

2024-01-24 01:50 UTC, vicroms commented on vcpkg/concepts/supported-hosts.md
> +  aren't merged.
```suggestion
  Configurations that are known no to work for some reason. In general, PRs fixing only these platforms
  are not accepted.
```

2024-01-24 05:18 UTC, dg0yt commented on vcpkg/concepts/supported-hosts.md
> +  * rpm-based platforms: `dnf install git curl zip unzip pkgconfig`
From the issues we know that macOS and Linux users don't get very far without `autoconf autoconf-archive automake make libtool`.

2024-01-24 05:18 UTC, dg0yt commented on vcpkg/concepts/supported-hosts.md
> +  * rpm-based platforms: `dnf install git curl zip unzip pkgconfig`
And maybe `python3`.

2024-01-26 21:32 UTC, data-queue commented on vcpkg/concepts/supported-hosts.md
> +
```suggestion
### Android
* Linux 64-bit Android NDK version 25c
```

2024-01-26 22:50 UTC, vicroms commented on vcpkg/concepts/supported-hosts.md
> +  * rpm-based platforms: `dnf install git curl zip unzip pkgconfig`
```suggestion
  * rpm-based platforms: `dnf install git curl zip unzip pkgconfig`

For Linux and macOS users we also recommend to install the following packages: `autoconf`, `autoconf-archive`, `automake`, `make` and `libtool`. While not required, these packages are used often by libraries available in vcpkg.
```

2024-01-26 22:52 UTC, vicroms approved these changes

2024-01-26 22:53 UTC, merged