Updated overview page
microsoft/vcpkg-docs pull request #358
Opened 2024-07-12 05:10 UTC by AugP

Fixes #315 (some typos) and updates some out-of-date information.

2024-07-15 19:03 UTC, ras0219-msft approved these changes

2024-07-15 20:12 UTC, vicroms requested changes

2024-07-15 20:12 UTC, vicroms commented on vcpkg/get_started/overview.md
> +vcpkg is a free and open-source C/C++ package manager maintained by Microsoft and the C++ community. vcpkg runs on Windows, macOS, and Linux (see [Supported hosts](../concepts/supported-hosts.md)) an
Sentences in this paragraph seem to run longer than they should.  We should consider reformatting it into something nicer.

```suggestion
vcpkg is a free and open-source C/C++ package manager maintained by Microsoft and the C++ community that runs on Windows, macOS, and Linux (see [Supported hosts](../concepts/supported-hosts.md)). vcpkg is a C++ tool at heart and is written in C++ and CMake scripts. It is designed from the ground up to address the unique pain points of the C/C++ developer experience.

Adopt vcpkg to enjoy these benefits:

* A large, curated, and ever-growing registry of open-source libraries.
* Enterprise-ready features designed to facilitate your development workflows.
* Support for any [build and project system](../concepts/build-system-integration.md) with CMake and MSBuild projects supported as first-class experiences.
* Target virtually any platform or architecture using [customizable triplets](../concepts/triplets.md)
```

2024-07-15 20:57 UTC, BillyONeal approved these changes
LGTM assuming Victor's comment is fixed

2024-07-26 19:51 UTC, AugP commented
@vicroms made a few changes to the opening section; let me know if it needs more work.

2024-07-30 17:59 UTC, vicroms approved these changes

2024-07-30 17:59 UTC, merged